Adding "require-client" targets.

diff --git a/mongo/_dumps/Makefile b/mongo/_dumps/Makefile
--- a/mongo/_dumps/Makefile
+++ b/mongo/_dumps/Makefile
@@ -1,4 +1,10 @@
 all: setup
 
-setup:
+require-client:
+	if [ -z "$(which mongo)" ]; then \
+		echo 'Missing "mongo" command. Please install the MongoDB client and try again.' && \
+		exit 1; \
+	fi
+
+setup: require-client
 	mongo upperio_tests --eval 'db.addUser("upperio_tests", "upperio_secret")'
diff --git a/mysql/Makefile b/mysql/Makefile
--- a/mysql/Makefile
+++ b/mysql/Makefile
@@ -4,7 +4,13 @@ BENCHTIME ?= 10s
 build:
 	go build && go install
 
-reset-db:
+require-client:
+	if [ -z "$(which mysql)" ]; then \
+		echo 'Missing "mysql" command. Please install the MySQL client and try again.' && \
+		exit 1; \
+	fi
+
+reset-db: require-client
 	$(MAKE) reset-db -C _dumps
 
 test: reset-db
diff --git a/postgresql/Makefile b/postgresql/Makefile
--- a/postgresql/Makefile
+++ b/postgresql/Makefile
@@ -4,7 +4,13 @@ BENCHTIME ?= 10s
 build:
 	go build && go install
 
-reset-db:
+require-client:
+	if [ -z "$(which psql)" ]; then \
+		echo 'Missing "psql" command. Please install the PostgreSQL client and try again.' && \
+		exit 1; \
+	fi
+
+reset-db: require-client
 	$(MAKE) reset-db -C _dumps
 
 test: reset-db
diff --git a/ql/Makefile b/ql/Makefile
--- a/ql/Makefile
+++ b/ql/Makefile
@@ -3,7 +3,13 @@ BENCHTIME ?= 10s
 build:
 	go build && go install
 
-reset-db:
+require-client:
+	if [ -z "$(which ql)" ]; then \
+		echo 'Missing "ql" command. Please install the QL cli tool and try again.' && \
+		exit 1; \
+	fi
+
+reset-db: require-client
 	$(MAKE) reset-db -C _dumps
 
 test: reset-db
diff --git a/sqlite/Makefile b/sqlite/Makefile
--- a/sqlite/Makefile
+++ b/sqlite/Makefile
@@ -3,7 +3,13 @@ BENCHTIME ?= 10s
 build:
 	go build && go install
 
-reset-db:
+require-client:
+	if [ -z "$(which sqlite3)" ]; then \
+		echo 'Missing "sqlite3" command. Please install SQLite3 and try again.' && \
+		exit 1; \
+	fi
+
+reset-db: require-client
 	$(MAKE) reset-db -C _dumps
 
 test: reset-db
