Attempt to fix Makefiles with require-client.

diff --git a/mongo/Makefile b/mongo/Makefile
--- a/mongo/Makefile
+++ b/mongo/Makefile
@@ -4,9 +4,17 @@ BENCHTIME ?= 10s
 build:
 	go build && go install
 
-test:
+require-client:
+	if [ -z "$$(which mongo)" ]; then \
+		echo 'Missing "mongo" command. Please install the MongoDB client and try again.' && \
+		exit 1; \
+	fi
+
+reset-db: require-client
+
+test: reset-db
 	go test -v
 	$(MAKE) -C _example
 
-bench:
+bench: reset-db
 	go test -v -test.bench=. -test.benchtime=$(BENCHTIME) -benchmem
